repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    -   id: black
        args: ['--config=./pyproject.toml']
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.237
    hooks:
    -   id: ruff
-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.15.0
    hooks:
    -   id: eslint
        files: src\/static\/js\/[^.]+.js
-   repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
    -   id: prettier
        files: \.js(on)?
        args: ['--ignore-path=./.eslintignore', '--write']
