[tool.black]
line-length = 100
target-version = ['py39']
extend-exclude = '''
(
  ^/migrations\/
)
'''
force-exclude = '''
# Needed for pre-commit
(
  ^/migrations\/
)
'''

[tool.pytest.ini_options]
addopts = "-ra --cov"
testpaths = [
    "tests"
]
pythonpath = ['.']

[tool.coverage.paths]
source = ["src"]

[tool.coverage.report]
show_missing = true
fail_under = 100
